#! /bin/bash

cd ./src

cc main.c lib.c level.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o game

if [ $? -eq 0 ]; then
    printf "\n\033[0;32mbuild succselfully \n"
    mv game ../builds
else
    printf "\n\033[0;31mbuild faild \n"
fi
